from youtube_statistics import YTstats

# paste the API key generated by you here
API_KEY = "AIzaSyA-0KfpLK04NpQN1XghxhSlzG-WkC3DHLs"

# paste the channel id here
# channel_id = "UC0RhatS1pyxInC00YKjjBqQ"
channel_id = "UC3HS6gQ79jjn4xHxogw0HiA"  # Magnet Brains

yt = YTstats(API_KEY, channel_id)
yt.get_channel_statistics()
yt.dump()
